# Analiza danych przestrzennych - ćwiczenia laboratoryjne 2025/2026

Ten notatnik zalicza się do grupy zestawów zadań, na podstawie których odbywa się zaliczenie ćwiczeń i podlega zwrotowi do oceny w ustalonym na zajęciach terminie.

Uwagi i wytyczne ogólne dotyczące uzupełniania i oceny notatnika:
- Podczas wykonywania zadań należy korzystać wyłącznie z pakietów zaimportowanych na początku notatnika oraz z pakietów wchodzących w skład standardowej biblioteki Pythona, które można zaimportować samodzielnie we wskazanej komórce notatnika.
- Swoje rozwiązania należy wprowadzać wyłącznie w miejce następujących fragmentów kodu:<br/> `# YOUR CODE HERE`<br/> `raise NotImplementedError()`<br/> 
a odpowiedzi tekstowe w komórkach oznaczonych hasłem:<br/> 
`YOUR ANSWER HERE`<br/> 
Nie należy w żaden sposób modyfikować pozostałych fragmentów kodu oraz innych elementów notatnika, w szczególności dodawać lub usuwać komórek oraz zmieniać nazwy pliku.
- Jeżeli zestaw zadań wymaga skorzystania z fragmentów kodu opracowanego w ramach wcześniejszych zestawów zadań należy je umieścić we wskazanej komórce notatnika.
- Otrzymywane wyniki i odpowiedzi mają być rezultatem wykonania napisanego kodu, odpowiedzi uzupełniane manualnie nie podlegają ocenie.
- Zawarte w notatniku automatyczne testy mają charakter poglądowy. Dotyczą one wybranych aspektów zadań i mają na celu wyłapać podstawowe błędy. Przejście przez kod wszystkich testów nie oznacza, że zadanie jest wykonane w całości poprawnie i zostanie ocenione na maksymalną liczbę punktów.
- Zadania należy wykonać w taki sposób, aby podczas wykonywania kodu nie zostały wyświetlone żadne ostrzeżenia.
- Zadania, które powodują wyświetlenie komunikatu o błędzie przerywającym wykonywanie kodu nie podlegają ocenie.
- W treści niektórych zadań mogą znaleźć się przykładowe schematy ich rozwiązania lub przykładowe schematy istotnych części rozwiązania. Nie zawsze są to rozwiązania optymalne pod kątem długości kodu lub prostoty rozwiązania.  Ich celem jest klarowne rozbicie pracy na kroki i ułatwienie samodzielnej weryfikacji wyników na każdym etapie. Należy je traktować wyłącznie poglądowo, a nie jako jedyne dopuszczalne rozwiązania. Ocenie podlega poprawność merytoryczna rozwiązania, jego kompletność oraz zgodność z wymaganiami, a nie konkretna forma zapisu.
- Dla zachowania przejrzystości i łatwego odnajdywania informacji w treści zadań podawane są pełne nazwy funkcji i klas wraz z nazwami pakietów (np. `pandas.read_csv()`, `geopandas.GeoDataFrame.to_crs`). W notatniku te same obiekty są dostępne przez skrótowe aliasy (np. `pd.read_csv()`, `gpd.GeoDataFrame.to_crs`).

Uwagi i wytyczne ogólne dotyczące wizualizacji wyników:
- Wszystkie wykresy powinny być wykonane w jednolitym, przejrzystym i czytelnym stylu, posiadać odpowiednio dobrane proporcje i zakresy wartości osi.
- Figury powinny mieć ustawione białe tło, tak, aby niezależnie od ustawień notatnika wszystkie elementy wykresów były dobrze widoczne (domyślnie tło jest przeźroczyste co może powodować problemy w notatnikach z ustawionym ciemnym tłem). Rozmiar poziomy figur nie powinien przekraczać 20 cali.
- Wykresy oraz ich osie powinny mieć nadane tytuły. Jeżeli w obrębie figury znajduje się więcej niż jeden wykres to figura również powinna mieć nadany tytuł.

Przed odesłaniem zestawu zadań do oceny proszę uzupełnić komórkę z danymi autorów rozwiązania (nazwa zespołu oraz imiona, nazwiska i numery indeksów członków zespołu) oraz upewnić się, że notatnik działa zgodnie z oczekiwaniami. W tym celu należy skorzystać z opcji **Restart Kernel and Run All Cells...** dostępnej na górnej belce notatnika pod symbolem $\blacktriangleright\blacktriangleright$.

Nazwa zespołu:
Członkowie:

---

## Zestaw zadań 4: Folium - mapy interaktywne

In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
import folium
import folium.plugins

In [2]:
# Miejsce do importu pakietów wchodzących w skład standardowej biblioteki Pythona oraz ustawienie opcji wykorzystywanych pakietów

### Informacje dodatkowe

W treści zadań wszystkie nazwy klas i funkcji są podawane w pełnej postaci (np. `folium.folium.Map`, `folium.map.Marker`), aby jednoznacznie wskazać ich położenie w strukturze i dokumentacji pakietu.
W praktyce jednak można - i warto - korzystać z krótszych nazw (np. `folium.Marker`, `folium.Map`), ponieważ dla wygody użytkownika są one udostępnione bezpośrednio w głównym module folium. Wyjątek stanowią pluginy (np. `folium.plugins.MarkerCluster`), które nie są udostępnione w module głównym, dlatego należy je zawsze wywoływać z pełną ścieżką.

W teści zadań pojawiają się również funkcje `branca.element.Element.add_to()` i `branca.element.Element.add_child()`. Pochodzą one z klasy bazowej Element w bibliotece branca, z której Folium korzysta. Obiekty Folium (np. `Map`, `Marker`, `FeatureGroup`) dziedziczą tę metodę. Możemy zatem wywoływać na nich te funkcje (np. `folium.map.Marker().add_to()`).

### Zadanie 1: Podstawowe markery, ustawienia mapy i kontrola widoczności jej elementów [10 pkt]

Poniższe zmienne zawierają współrzędne kilku obiektów w Krakowie:
 - `a0` - punktowe oznaczenie budynku głównego AGH,
 - `wawel` - punktowe oznaczenie Zamku Królewskiego na Wawelu,
 - `rynek` - punktowe oznaczenie Rynku Głównego,
 - `karmelicka` - zestaw współrzędnych oznaczających przebieg ulicy Karmelickiej,
 - `blonia` - zestaw współrzędnych oznaczających granice Błoń.

In [3]:
a0 = [50.064548, 19.923296]

wawel = [50.054259, 19.935545]

rynek = [50.061697, 19.937356]

karmelicka = [[50.0634159, 19.9329681], [50.0634275, 19.9329547], [50.0634901, 19.9328898], [50.0635753, 19.9328016], [50.0636564, 19.9327195],
             [50.0637625, 19.932613], [50.0644251, 19.9319687], [50.06454, 19.9318539], [50.064641, 19.9317531], [50.0647203, 19.9316739],
             [50.0647589, 19.9316326], [50.0647589, 19.9316326], [50.0648095, 19.9315771], [50.0650312, 19.9313187], [50.0650312, 19.9313187],
             [50.0653207, 19.9309698], [50.0653681, 19.9309133], [50.0654537, 19.930806], [50.065688, 19.9305147], [50.0665715, 19.9294166],
             [50.0667218, 19.9292349], [50.066808, 19.9291359], [50.066883, 19.9290488], [50.066921, 19.9290055], [50.0670031, 19.9289093],
             [50.067351, 19.9285085], [50.0674192, 19.9284287], [50.0674835, 19.9283548], [50.0681583, 19.9275769], [50.0683923, 19.9273071],
             [50.0683923, 19.9273071], [50.0685642, 19.9271077], [50.0686383, 19.9270218], [50.0686383, 19.9270218], [50.0688152, 19.9268167],
             [50.0688152, 19.9268167], [50.0688856, 19.9267351], [50.0690011, 19.9266041]]

blonia = [[50.059374, 19.9068228], [50.058345, 19.9051515], [50.0589615, 19.9040932], [50.0592326, 19.9035986], [50.059492, 19.9030558],
         [50.0602093, 19.9012175], [50.0604061, 19.9010762], [50.0614121, 19.9018127], [50.062412, 19.902546], [50.0592513, 19.9231318],
         [50.0592212, 19.9231335], [50.0590566, 19.9219675], [50.0586649, 19.9192393], [50.0585154, 19.9181629], [50.0582089, 19.9160288],
         [50.0579078, 19.9139449], [50.0572063, 19.909055], [50.0570365, 19.907823], [50.0570248, 19.9076985], [50.0570248, 19.9075061],
         [50.0570524, 19.9077121], [50.0571219, 19.9078348], [50.057181, 19.9078745], [50.0572328, 19.9078169], [50.0573294, 19.9079877],
         [50.0580153, 19.9090244], [50.0588218, 19.9077734], [50.0587998, 19.9077394], [50.059374, 19.9068228]]

#### a)

Przygotuj interaktywną mapę zgodnie z poniższymi wytycznymi:
1) Korzystając z `folium.folium.Map` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.folium.Map) przygotuj i zapisz do zmiennaj `m1` interaktywną mapę. Ustaw:
    - lokalizację domyślną mapy na współrzędne [50.0647, 19.9450],
    - minimalne, startowe i maksymalne przybliżenie mapy odpowiednio na 12, 14 i 16,
    - widoczność podziałki skali.
    
2) Przygotuj i dodaj do mapy następujące obiekty:
    - `folium.map.Marker` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Marker) - lokalizacja głównego budynku AGH. Zdefiniuj argument `icon` korzystając z `folium.map.Icon` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Icon), w obrębie którego wybierz inny od domyślnego kolor ikony oraz odpowiadające lokalizacji oznaczenie (np. budynek z kolumnami). Zwróć uwagę na fakt, że w zależności od wybranego źródła ikony ([Bootstrap](https://getbootstrap.com/docs/3.3/components/) lub [Font Awesome](https://fontawesome.com/)) należy odpowiednio ustawić wartość argumentu `prefix`;
    - `folium.vector_layers.CircleMarker` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.vector_layers.CircleMarker) - lokalizacja Zamku Królewskiego na Wawelu. Ustaw promień markera na 10 px, inny niż domyślny kolor oraz półprzeźroczyste wypełnienie;
    - `folium.vector_layers.Circle` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.vector_layers.Circle) - Rynek Główny. Ustaw promień na 150 m, inny niż domyślny kolor oraz półprzeźroczyste wypełnienie;
    - `folium.vector_layers.PolyLine` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.vector_layers.PolyLine) - ulica Karmelicka. Ustaw inny niż domyślny kolor oraz grubość linii;
    - `folium.vector_layers.Polygon`[[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.vector_layers.Polygon) - Błonia. Ustaw inny niż domyślny kolor obramowania i wypełnienia, grubość linii obramowania oraz półprzeźroczyste wypełnienie.</br>

    Dla każdego z obiektów określ wartości argumentów `tooltip` (nazwa obiektu wyświetlająca się po najechaniem na niego kursorem) i `popup` (dodatkowe informacje, np. z Wikipedii, wyświetlające się po kliknięciu na niego kursorem). Dodaj oznaczenia do mapy korzystając z funkcji `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element).

3) Wyświetl wynikową mapę wywołując w ostatniej linijce komórki zmienną `m1`.

In [19]:
m1 = folium.Map(
    location = [50.0647, 19.9450],
    min_zoom = 12,
    max_zoom = 16,
    zoom_start = 14,
    control_scale=True
)

agh = folium.map.Marker(
    location=a0,
    tooltip="AGH - Budynek Główny",
    popup="Akademia Górniczo-Hutnicza (AGH) – główny budynek uczelni.",
    icon=folium.map.Icon(color="green", icon = 'university', prefix = 'fa')
)
agh.add_to(m1)

zamek = folium.vector_layers.CircleMarker(
    location=wawel,
    radius=10,
    color = 'brown',
    fill = True,
    fill_opacity = 0.5,
    tooltip = "Zamek Królewski na Wawelu",
    popup = "Zabytkowy zamek obronno-rezydencyjny w Krakowie, na wzgórzu Wawelskim."
)
zamek.add_to(m1)

rynek_m = folium.vector_layers.Circle(
    location=rynek,
    radius=150,
    color= 'red',
    fill = True,
    fill_opacity = 0.5,
    tooltip = "Rynek Główny",
    popup = "Plac w Krakowie, w dzielnicy I Stare Miasto, na Starym Mieście."
)
rynek_m.add_to(m1)

ulica = folium.vector_layers.PolyLine(
    locations=karmelicka,
    color = 'blue',
    weight=4,
    tooltip = "Ulica Karmelicka",
    popup = "Główna ulica dawnej dzielnicy Piasek. Stanowi przedłużenie ulicy Szewskiej i łączy ją z placem Inwalidów."
)
ulica.add_to(m1)

blonie = folium.vector_layers.Polygon(
    locations=blonia,
    color = "darkgreen",
    weight = 3,
    fill = True,
    fill_opacity = 0.3,
    fill_color = "green",
    tooltip = "Błonia",
    popup = "Zabytkowy park miejski w postaci rozległej łąki"
)
blonie.add_to(m1)

m1

#### b)

Przygotuj interaktywną mapę zgodnie z poniższymi wytycznymi:
1) Korzystając z `folium.folium.Map` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.folium.Map) przygotuj i zapisz do zmiennaj `m2` interaktywną mapę. Ustaw:
    - lokalizację domyślną mapy na współrzędne [50.0647, 19.9450],
    - minimalne, startowe i maksymalne przybliżenie mapy odpowiednio na 12, 14 i 16,
    - widoczność podziałki skali.

2) Korzystając z `folium.map.FeatureGroup` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.FeatureGroup) przygotuj i zapisz do zmiennych trzy grupy o nazwach "Oznaczenia punktowe", "Oznaczenia liniowe" i "Oznaczenia powierzchniowe". 

3) Przygotuj i dodaj do grup następujące obiekty:
    - `folium.map.Marker` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Marker) - lokalizacja głównego budynku AGH. Zdefiniuj argument `icon` korzystając z `folium.map.Icon` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Icon), w obrębie którego wybierz inny od domyślnego kolor ikony oraz odpowiadające lokalizacji oznaczenie (np. budynek z kolumnami). Zwróć uwagę na fakt, że w zależności od wybranego źródła ikony ([Bootstrap](https://getbootstrap.com/docs/3.3/components/) lub [Font Awesome](https://fontawesome.com/)) należy odpowiednio ustawić wartość argumentu `prefix`;
    - `folium.vector_layers.CircleMarker` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.vector_layers.CircleMarker) - lokalizacja Zamku Królewskiego na Wawelu. Ustaw promień markera na 10 px, inny niż domyślny kolor oraz półprzeźroczyste wypełnienie;
    - `folium.vector_layers.Circle` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.vector_layers.Circle) - Rynek Główny. Ustaw promień na 150 m, inny niż domyślny kolor oraz półprzeźroczyste wypełnienie;
    - `folium.vector_layers.PolyLine` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.vector_layers.PolyLine) - ulica Karmelicka. Ustaw inny niż domyślny kolor oraz grubość linii;
    - `folium.vector_layers.Polygon`[[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.vector_layers.Polygon) - Błonia. Ustaw inny niż domyślny kolor obramowania i wypełnienia, grubość linii obramowania oraz półprzeźroczyste wypełnienie.</br>

    Dla każdego z obiektów określ wartości argumentów `tooltip` (nazwa obiektu wyświetlająca się po najechaniem na niego kursorem) i `popup` (dodatkowe informacje, np. z Wikipedii, wyświetlające się po kliknięciu na niego kursorem). Dodaj oznaczenia do odpowiednich grup korzystając z funkcji `branca.element.Element.add_child()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element).

4) Dodaj przygotowane grupy do mapy korzystając z funkcji `branca.element.Element.add_child()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element).

5) Korzystając z `folium.raster_layers.TileLayer` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.raster_layers.TileLayer) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) dodaj do mapy dodatkową mapę podkładową 'CartoDB positron'. Ustaw brak domyślnej widoczności tej mapy podkładowej.

6) Korzystając z `folium.map.LayerControl` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.LayerControl) wygeneruj kontrolę warstw i dodaj ją do mapy korzystając z funkcji `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element).

8) Wyświetl wynikową mapę wywołując w ostatniej linijce komórki zmienną `m2`.

9) Przetestuj kontrolę widoczności elementów mapy (rozwijane menu w jej prawym górnym narożniku).

In [25]:
m2 = folium.Map(
    location = [50.0647, 19.9450],
    min_zoom = 12,
    max_zoom = 16,
    zoom_start = 14,
    control_scale=True
)

oznaczenia_punktowe = folium.map.FeatureGroup(name="Oznaczenia punktowe")
oznaczenia_liniowe = folium.map.FeatureGroup(name="Oznaczenia liniowe")
oznaczenia_powierzchniowe = folium.map.FeatureGroup(name="Oznaczenia powierzchniowe")

oznaczenia_punktowe.add_child(agh)
oznaczenia_liniowe.add_child(ulica)

for i in [zamek, rynek_m, blonie]:
    oznaczenia_powierzchniowe.add_child(i)

m2.add_child(oznaczenia_liniowe)
m2.add_child(oznaczenia_powierzchniowe)
m2.add_child(oznaczenia_punktowe)

mapa_dodatkowa = folium.raster_layers.TileLayer(
    tiles='CartoDB positron',
    name='CartoDB positron', 
    control = True,
    overlay = False,
    show = False
)
mapa_dodatkowa.add_to(m2)

kontrola_warstw = folium.map.LayerControl(
    position = 'topright'
)
kontrola_warstw.add_to(m2)

m2

### Zadanie 2: Wykorzystanie danych z tablic oraz pluginy [8 pkt]

Poniższe zmienne zawierają obszar Krakowie (`city`) oraz lokalizacje pomników przyrody znajdujących się na jego terenie (`natural_monuments`).

In [26]:
city = gpd.read_file("KRK_data.gpkg", layer='city')
city

    Nazwa                                           geometry
0  Kraków  POLYGON ((571937.571 237575.079, 571934.41 237...

In [27]:
natural_monuments = gpd.read_file("KRK_data.gpkg", layer='natural monuments')
natural_monuments = natural_monuments[["id", "obiekt", "gatunek",  "geometry"]]
natural_monuments.head()

,id,obiekt,gatunek,geometry
0,PomnikiPrzyrodyPunktowe.fid--452bf94a_1982e2c8...,drzewo,Kasztanowiec zwyczajny (Kasztanowiec biały) - ...,POINT (564361.751 243290.721)
1,PomnikiPrzyrodyPunktowe.fid--452bf94a_1982e2c8...,drzewo,Dąb szypułkowy - Quercus robur,POINT (567620.279 242298.868)
2,PomnikiPrzyrodyPunktowe.fid--452bf94a_1982e2c8...,drzewo,Wiąz szypułkowy - Ulmus laevis (Ulmus pedencul...,POINT (565311.6 245928.58)
3,PomnikiPrzyrodyPunktowe.fid--452bf94a_1982e2c8...,drzewo,Sosna zwyczajna (Sosna pospolita) - Pinus sylv...,POINT (566788.38 238272.62)
4,PomnikiPrzyrodyPunktowe.fid--452bf94a_1982e2c8...,drzewo,Dąb szypułkowy - Quercus robur,POINT (571274.81 239510.98)

#### a)

Przygotuj interaktywną mapę zgodnie z poniższymi wytycznymi:

1) Korzystając z `folium.folium.Map` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.folium.Map) przygotuj i zapisz do zmiennaj `m3` interaktywną mapę. Ustaw:
    - lokalizację domyślną mapy na współrzędne [50.05, 20.00],
    - minimalne, startowe i maksymalne przybliżenie mapy odpowiednio na 8, 12 i 16,
    - widoczność podziałki skali.

2) Korzystając z `folium.features.GeoJson` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.features.GeoJson) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) dodaj do mapy poligon miasta Krakowa. Ustaw inny niż domyślny kolor obramowania i wypełnienia, grubość linii obramowania oraz półprzeźroczyste wypełnienie.
   
3) Korzystając z `folium.features.GeoJson` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.features.GeoJson) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) dodaj do mapy punktowe oznaczenia lokalizacji pomników przyrody. Zdefiniuj argument `marker` za pomocą `folium.map.Marker` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Marker). Ustaw argument markera `icon` korzystając z `folium.map.Icon` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Icon), w obrębie którego wybierz inny od domyślnego kolor ikony oraz odpowiadające lokalizacji oznaczenie (np. drzewo). Zwróć uwagę na fakt, że w zależności od wybranego źródła ikony ([Bootstrap](https://getbootstrap.com/docs/3.3/components/) lub [Font Awesome](https://fontawesome.com/)) należy odpowiednio ustawić wartość argumentu `prefix`. Zdefiniuj wartość argumentu `tooltip` korzystając z `folium.features.GeoJsonTooltip` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.features.GeoJsonTooltip) tak, aby po najechaniu kursorem na marker wyświetlała się informacja o gatunku drzewa. 
   
4) Korzystając z `folium.plugins.MiniMap` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.plugins.MiniMap) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) dodaj minimapę. Ustaw argumenty tak, aby mapa była od razu widoczna w rozwiniętej formie, nie jako sama ikona.

5) Wyświetl wynikową mapę wywołując w ostatniej linijce komórki zmienną `m3`.

In [30]:
m3 = folium.Map(
    location = [50.05, 20.00],
    min_zoom = 8,
    max_zoom = 16,
    zoom_start = 12,
    control_scale=True
)

krakow = folium.features.GeoJson(
    data = city,
    color = 'black',
    weight = 1,
    fill = True,
    fill_opacity = 0.15,
    fill_color = "darkgreen"  
)
krakow.add_to(m3)

pomniki = folium.features.GeoJson(
    data = natural_monuments,
    marker = folium.map.Marker(
        icon=folium.map.Icon(color="green", icon = 'tree', prefix = 'fa')
    ),
    tooltip=folium.features.GeoJsonTooltip(fields=["gatunek"], aliases=["Gatunek: "])
)
pomniki.add_to(m3)

minimapa = folium.plugins.MiniMap(
    toggle_display = False,
    minimized=False,
    width = 150, 
    height = 150
)
minimapa.add_to(m3)

m3

#### b)

Przygotuj interaktywną mapę zgodnie z poniższymi wytycznymi:

1) Korzystając z `folium.folium.Map` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.folium.Map) przygotuj i zapisz do zmiennaj `m4` interaktywną mapę. Ustaw:
    - lokalizację domyślną mapy na współrzędne [50.05, 20.00],
    - minimalne, startowe i maksymalne przybliżenie mapy odpowiednio na 8, 12 i 16,
    - widoczność podziałki skali.

2) Korzystając z `folium.features.GeoJson` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.features.GeoJson) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) dodaj do mapy poligon miasta Krakowa. Ustaw inny niż domyślny kolor obramowania i wypełnienia, grubość linii obramowania oraz półprzeźroczyste wypełnienie.

3) Korzystając z `folium.plugins.MarkerCluster` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.plugins.MarkerCluster) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) zapisz do zmiennej i dodaj do mapy pusty klaster oznaczeń punkowych.

4) Dokonaj konwersji układu odniesienia danych zawartych w zmiennej `natural_monuments` do `EPSG:4326` (długość i szerokość geograficzna), zapisz wynik do zmiennej o innej nazwie, np. `natural_monuments_deg`.

5) W pętli `for` dokonaj iteracji po kolejnych wierszach tablicy z lokalizacjami pominków przyrody. W każdej iteracji, korzystając z `folium.map.Marker` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Marker) stwórz marker i dodaj go do klastra korzystając z `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element). Ustaw argument markera icon korzystając z `folium.map.Icon` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Icon), w obrębie którego wybierz inny od domyślnego kolor ikony oraz odpowiadające lokalizacji oznaczenie (np. drzewo). Zwróć uwagę na fakt, że w zależności od wybranego źródła ikony ([Bootstrap](https://getbootstrap.com/docs/3.3/components/) lub [Font Awesome](https://fontawesome.com/)) należy odpowiednio ustawić wartość argumentu `prefix`. Zdefiniuj wartość argumentu `tooltip` tak, aby po najechaniu kursorem na marker wyświetlała się informacja o gatunku drzewa. Zwróć uwagę, że w układzie geograficznym współrzędne są odwrócone względem geometrii obiektów w tablicy GeoPandas, więc współrzędne markera (`location`) należy definiować jako [y, x], a nie [x, y].

6) Wyświetl wynikową mapę wywołując w ostatniej linijce komórki zmienną `m4`.

In [39]:
m4 = folium.Map(
    location = [50.05, 20.00],
    min_zoom = 8,
    max_zoom = 16,
    zoom_start = 12,
    control_scale=True
)

krakow.add_to(m4)

marker_cluster = folium.plugins.MarkerCluster(name = "Klaster Pomników Przyrody")

natural_monuments_deg = natural_monuments.to_crs("EPSG:4326")

for i in natural_monuments_deg.index:
    loc = natural_monuments_deg.loc[i, "geometry"]
    marker = folium.map.Marker(
        location = [loc.y, loc.x],
        icon = folium.map.Icon(color='green', icon='tree', prefix='fa'),
        tooltip=str(natural_monuments_deg.loc[i, "gatunek"])
    )
    marker.add_to(marker_cluster)

marker_cluster.add_to(m4)

m4

### Zadanie 3: Infrastruktura turystyczna Tatrzańskiego Parku Narodowego [10 pkt]

Poniższe zmienne zawierają obszar Tatrzańskiego Parku Narodowego (`TPN_area`), przebieg wybranych szlaków turystycznych na jego obszarze (`TPN_trails`), lokalizacje schronisk (`TPN_shelters`) oraz przebieg kolejki linowej na Kasprowy Wierch (`TPN_cable_coordinates`).

In [40]:
TPN_area = gpd.read_file("TPN_data.gpkg", layer='area')
TPN_area

                      Nazwa                                           geometry
0  Tatrzański Park Narodowy  MULTIPOLYGON (((20.02063 49.30323, 20.02084 49...

In [41]:
TPN_trails = gpd.read_file("TPN_data.gpkg", layer='trails')
TPN_trails.head(1)

,Nazwa,Kolor,Czas przejścia,Dystans [km],geometry
0,Gubałówka - Kiry,green,1:10 h / 1:15 h,None,"MULTILINESTRING ((19.86893 49.27547, 19.86897 ..."

In [42]:
TPN_shelters = gpd.read_file("TPN_data.gpkg", layer='shelters')
TPN_shelters.head(1)

                             Nazwa                   geometry
0  Schronisko PTTK Hala Kondratowa  POINT (19.95168 49.24988)

In [43]:
TPN_cable_coordinates = [[49.2692868, 19.9792009], [49.2682375, 19.9788734], [49.2649274, 19.9778561], [49.2607109, 19.976571],
                         [49.25201, 19.9738909], [49.2518221, 19.9737025], [49.2472869, 19.9758811], [49.2441867, 19.9773712],
                         [49.2400547, 19.9793381], [49.2329527, 19.9827413], [49.2329213, 19.9827571]]

Przygotuj interaktywną mapę zgodnie z poniższymi wytycznymi:

1) Korzystając z `folium.folium.Map` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.folium.Map) przygotuj i zapisz do zmiennaj `m5` interaktywną mapę. Ustaw:
    - lokalizację domyślną mapy na współrzędne [49.25, 19.95],
    - minimalne, startowe i maksymalne przybliżenie mapy odpowiednio na 12, 12 i 14,
    - widoczność podziałki skali.

2) Korzystając z `folium.features.GeoJson` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.features.GeoJson) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) dodaj do mapy poligon Tatrzańskiego Parku Narodowego. Ustaw inny niż domyślny kolor obramowania i wypełnienia, grubość linii obramowania oraz półprzeźroczyste wypełnienie.

3) Korzystając z `folium.plugins.AntPath` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.plugins.AntPath) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) dodaj do mapy przebieg kolejki na Kasprowy Wierch. Ustaw inne od domyślnych wartości argumentów odpowiedzialnych za kolor i wzorzec ścieżki. Zdefiniuj wartość argumentu `tooltip` tak, aby po najechaniu kursorem na obiekt wyświetlała się jego nazwa.
4) Korzystając z `folium.features.GeoJson` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.features.GeoJson) oraz `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element) dodaj do mapy przebieg szlaków turystycznych. Zdefiniuj argument `style_function` korzystając z funkcji `lambda` tak, aby każdemu szlakowi został przyporządkowany odpowiedni kolor z tablicy [[LINK]](https://python-visualization.github.io/folium/latest/user_guide/geojson/geojson_marker.html#Use-a-Circle-as-a-Marker). Zdefiniuj argumenty `tooltip` i `popup` korzystając odpowiednio z `folium.features.GeoJsonTooltip` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.features.GeoJsonTooltip) oraz `folium.features.GeoJsonPopup` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.features.GeoJsonPopup) tak aby po najechaniu kursorem na szlak pojawiała się jego nazwa, a po kliknięciu nazwa, kolor, czas przejścia szlaku i dystans.
5) W pętli `for` dokonaj iteracji po kolejnych wierszach tablicy z lokalizacjami schronisk. W każdej iteracji, korzystając z `folium.map.Marker` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.map.Marker) stwórz marker i dodaj go do mapy korzystając z `branca.element.Element.add_to()` [[LINK]](https://python-visualization.github.io/branca/element.html#branca.element.Element). Zdefiniuj wartość argumentu `tooltip` tak, aby po najechaniu kursorem na marker wyświetlała się informacja o nazwie schroniska. Zdefiniuj wartość argumentu `icon` korzystając z `folium.plugins.BeautifyIcon` [[LINK]](https://python-visualization.github.io/folium/latest/reference.html#folium.plugins.BeautifyIcon) tak, aby ikona ([Font Awesome](https://fontawesome.com/)) miała inne od domyślnych kolor oraz kształt i tematycznie odnosiła się do schroniska (np. domek, namiot). Zwróć uwagę, że w układzie geograficznym współrzędne są odwrócone względem geometrii obiektów w tablicy GeoPandas, więc współrzędne markera (`location`) należy definiować jako [y, x], a nie [x, y].
6) Wyświetl wynikową mapę wywołując w ostatniej linijce komórki zmienną `m5`.

In [73]:
m5 = folium.Map(
    location = [49.25, 19.95],
    min_zoom = 12,
    max_zoom = 14,
    zoom_start = 12,
    control_scale=True
)

tpn = folium.features.GeoJson(
    data=TPN_area,
    color='black',
    fill=True,
    fill_color='dark_green',
    fill_opacity=0.15,
    weight=1
)
tpn.add_to(m5)

kolejka = folium.plugins.AntPath(
    locations=TPN_cable_coordinates,
    color='black',
    weigth=4,
    tooltip = "Kolejka liniowa na Kasprowy Wierch"
)
kolejka.add_to(m5)

szlaki = folium.features.GeoJson(
    data=TPN_trails,
    style_function = lambda x: {"color": x["properties"]["Kolor"]},
    weight=3,
    tooltip=folium.features.GeoJsonTooltip(fields=["Nazwa"]),
    popup=folium.features.GeoJsonPopup(
        fields=["Nazwa", "Czas przejścia", "Kolor", "Dystans [km]"], 
        aliases=["Nazwa:", "Czas przejścia:", "Kolor:", "Dystans [km]:"]
    )
)
szlaki.add_to(m5)

for i in TPN_shelters.index:
    loc = TPN_shelters.loc[i, "geometry"]
    marker = folium.map.Marker(
        location = [loc.y, loc.x],
        icon = folium.plugins.BeautifyIcon(
            icon = "tent",
            icon_shape = "marker",
            border_color = "firebrick",
            background_color = "gold",
        ),
        tooltip=str(TPN_shelters.loc[i, "Nazwa"])
    )
    marker.add_to(m5)

m5